import type { ContentCard, HomepageCatalog, VenueCard } from "./types";

const image = {
  cinema:
    "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=900&q=80",
  concert:
    "https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?auto=format&fit=crop&w=900&q=80",
  comedy:
    "https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=900&q=80",
  stadium:
    "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=900&q=80",
  theatre:
    "https://images.unsplash.com/photo-1503095396549-807759245b35?auto=format&fit=crop&w=900&q=80",
  workshop:
    "https://images.unsplash.com/photo-1531058020387-3be344556be6?auto=format&fit=crop&w=900&q=80",
  gallery:
    "https://images.unsplash.com/photo-1561214115-f2f134cc4912?auto=format&fit=crop&w=900&q=80",
  food: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=900&q=80",
  arena:
    "https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=900&q=80",
};

export const mockCatalog: ContentCard[] = [
  {
    id: "movie-forest",
    slug: "the-last-forest",
    title: "The Last Forest",
    category: "Movie",
    image: image.cinema,
    city: "Mumbai",
    venue: "PVR: Jio World Drive",
    dateLabel: "In cinemas now",
    timeLabel: "Hindi, English",
    priceFrom: 220,
    rating: 8.6,
    badge: "Critics' pick",
    language: "Hindi, English",
    genre: "Drama, Mystery",
    duration: "2h 12m",
    eventType: "MOVIE",
    startsAt: "2026-08-24T18:30:00+05:30",
  },
  {
    id: "movie-indigo",
    slug: "indigo-summer",
    title: "Indigo Summer",
    category: "Movie",
    image: image.theatre,
    city: "Mumbai",
    venue: "Cinepolis: Seawoods",
    dateLabel: "In cinemas now",
    timeLabel: "Hindi",
    priceFrom: 190,
    rating: 8.1,
    language: "Hindi",
    genre: "Romance, Music",
    duration: "2h 04m",
    eventType: "MOVIE",
    startsAt: "2026-08-24T20:15:00+05:30",
  },
  {
    id: "movie-orbit",
    slug: "orbit-9",
    title: "Orbit 9",
    category: "Movie",
    image: image.gallery,
    city: "Mumbai",
    venue: "INOX: R City",
    dateLabel: "Opening Friday",
    timeLabel: "English, Hindi",
    priceFrom: 240,
    rating: 7.9,
    badge: "Early access",
    language: "English, Hindi",
    genre: "Sci-fi, Adventure",
    duration: "2h 20m",
    eventType: "MOVIE",
    startsAt: "2026-08-28T19:00:00+05:30",
  },
  {
    id: "moonlit-market",
    slug: "moonlit-market",
    title: "Moonlit Market",
    category: "Live Event",
    image: image.food,
    city: "Mumbai",
    venue: "NESCO Centre, Goregaon",
    dateLabel: "Sat, 30 Aug",
    timeLabel: "5:00 PM",
    priceFrom: 299,
    rating: 4.7,
    badge: "Selling fast",
    eventType: "FESTIVAL",
    startsAt: "2026-08-30T17:00:00+05:30",
  },
  {
    id: "designing-joy",
    slug: "designing-for-joy",
    title: "Designing for Joy",
    category: "Live Event",
    image: image.workshop,
    city: "Mumbai",
    venue: "Cultural Hall, Bandra",
    dateLabel: "Sun, 31 Aug",
    timeLabel: "11:00 AM",
    priceFrom: 349,
    rating: 4.8,
    eventType: "WORKSHOP",
    startsAt: "2026-08-31T11:00:00+05:30",
  },
  {
    id: "midnight-grove",
    slug: "midnight-grove-live",
    title: "Midnight Grove Live",
    category: "Concert",
    image: image.concert,
    city: "Mumbai",
    venue: "Mehboob Studios, Bandra",
    dateLabel: "Fri, 5 Sep",
    timeLabel: "7:30 PM",
    priceFrom: 899,
    rating: 4.9,
    badge: "Almost gone",
    eventType: "CONCERT",
    startsAt: "2026-09-05T19:30:00+05:30",
  },
  {
    id: "late-laughs",
    slug: "late-laughs-club",
    title: "Late Laughs Club",
    category: "Comedy",
    image: image.comedy,
    city: "Mumbai",
    venue: "The Habitat, Khar",
    dateLabel: "Tonight",
    timeLabel: "9:30 PM",
    priceFrom: 399,
    rating: 4.6,
    eventType: "COMEDY",
    startsAt: "2026-08-24T21:30:00+05:30",
  },
  {
    id: "mumbai-hoops",
    slug: "mumbai-hoops-night",
    title: "Mumbai Hoops Night",
    category: "Sports",
    image: image.arena,
    city: "Mumbai",
    venue: "NSCI Dome, Worli",
    dateLabel: "Sun, 7 Sep",
    timeLabel: "6:00 PM",
    priceFrom: 599,
    rating: 4.7,
    eventType: "SPORT",
    startsAt: "2026-09-07T18:00:00+05:30",
  },
  {
    id: "harbour-derby",
    slug: "harbour-derby",
    title: "Harbour Derby",
    category: "Sports",
    image: image.stadium,
    city: "Mumbai",
    venue: "Cooperage Ground",
    dateLabel: "Sun, 31 Aug",
    timeLabel: "7:00 PM",
    priceFrom: 249,
    rating: 4.6,
    eventType: "SPORT",
    startsAt: "2026-08-31T19:00:00+05:30",
  },
  {
    id: "glow-kayak",
    slug: "glow-kayak",
    title: "Glow Kayak After Dark",
    category: "Experience",
    image: image.gallery,
    city: "Mumbai",
    venue: "Powai Lake",
    dateLabel: "Sat, 30 Aug",
    timeLabel: "6:30 PM",
    priceFrom: 449,
    rating: 4.8,
    badge: "Small group",
    eventType: "ADVENTURE",
    startsAt: "2026-08-30T18:30:00+05:30",
  },
];

export const mockVenues: VenueCard[] = [
  {
    id: "nesco",
    name: "NESCO Centre",
    neighborhood: "Goregaon",
    city: "Mumbai",
    image: image.food,
    eventCount: 14,
    specialty: "Fairs, festivals, live acts",
  },
  {
    id: "habitat",
    name: "The Habitat",
    neighborhood: "Khar",
    city: "Mumbai",
    image: image.comedy,
    eventCount: 9,
    specialty: "Comedy and intimate shows",
  },
  {
    id: "opera",
    name: "Royal Opera House",
    neighborhood: "Charni Road",
    city: "Mumbai",
    image: image.theatre,
    eventCount: 7,
    specialty: "Music, theatre, culture",
  },
  {
    id: "dome",
    name: "NSCI Dome",
    neighborhood: "Worli",
    city: "Mumbai",
    image: image.arena,
    eventCount: 11,
    specialty: "Sports and big nights",
  },
];

const byCategory = (category: ContentCard["category"]) =>
  mockCatalog.filter((item) => item.category === category);

export const mockHomepageCatalog: HomepageCatalog = {
  city: "Mumbai",
  hero: mockCatalog[5],
  trending: [
    mockCatalog[3],
    mockCatalog[0],
    mockCatalog[6],
    mockCatalog[8],
    mockCatalog[9],
  ],
  recommendedMovies: byCategory("Movie"),
  liveEvents: [
    mockCatalog[3],
    mockCatalog[4],
    mockCatalog[9],
    mockCatalog[5],
    mockCatalog[6],
  ],
  concerts: [
    mockCatalog[5],
    mockCatalog[1],
    mockCatalog[3],
    mockCatalog[2],
    mockCatalog[4],
  ],
  comedy: [
    mockCatalog[6],
    mockCatalog[4],
    mockCatalog[0],
    mockCatalog[1],
    mockCatalog[3],
  ],
  sports: [
    mockCatalog[7],
    mockCatalog[8],
    mockCatalog[5],
    mockCatalog[3],
    mockCatalog[9],
  ],
  weekendExperiences: [
    mockCatalog[9],
    mockCatalog[4],
    mockCatalog[3],
    mockCatalog[5],
    mockCatalog[1],
  ],
  under499: [
    mockCatalog[0],
    mockCatalog[1],
    mockCatalog[3],
    mockCatalog[4],
    mockCatalog[6],
    mockCatalog[8],
    mockCatalog[9],
  ],
  popularVenues: mockVenues,
  personalized: [
    mockCatalog[0],
    mockCatalog[5],
    mockCatalog[6],
    mockCatalog[2],
    mockCatalog[9],
  ],
};
